//! Engine bootstrap data for `--no-checked` decode.
//!
//! [`ENGINE_CLASS_WARMUP`] is the menu trace's
//! `object_load_order[..None.MyLevel]` (153 entries). Mirrors the
//! explicit `StaticLoadObject` calls in SC's `game_main`
//! (xbe `0x1F370`) before it triggers the level load via
//! `StaticLoadObject(MapName, ULevel, ...)`. Some entries are
//! loaded explicitly by `game_main`; the rest cascade in via
//! property-tag and class-ref deserialization as the explicit ones
//! go through `verify_imports`. We don't distinguish those cases —
//! `load_object_by_full_name` is idempotent (no-op on the second
//! call), so iterating the full list reproduces the exact engine
//! state regardless of which entries were "really" explicit.
//!
//! `common.lin` is byte-identical across every map in the SC NTSC
//! build (verified via md5), so this same warmup applies to every
//! map. For non-NTSC builds (proto, demo) the entries that aren't
//! present resolve to `None` and the cascade continues; the
//! file_table-derived `present_packages` filter handles which
//! warmup-induced linker loads are physically realisable.

pub(crate) const ENGINE_CLASS_WARMUP: &[&str] = &[
    "Engine.GameEngine",
    "Echelon.ECanvas",
    "Engine.Input",
    "Core.Function",
    "Core.Struct",
    "Core.Field",
    "Core.Const",
    "Core.TextBuffer",
    "Core.Enum",
    "Core.LinkerLoad",
    "Core.Linker",
    "Core.LinkerSave",
    "Core.Commandlet",
    "Core.Factory",
    "Core.TextBufferFactory",
    "Core.Language",
    "Core.ByteProperty",
    "Core.Property",
    "Core.IntProperty",
    "Core.BoolProperty",
    "Core.FloatProperty",
    "Core.ObjectProperty",
    "Core.ClassProperty",
    "Core.NameProperty",
    "Core.StrProperty",
    "Core.FixedArrayProperty",
    "Core.ArrayProperty",
    "Core.MapProperty",
    "Core.StructProperty",
    "Core.System",
    "Core.Package",
    "Core.State",
    "Core.Class",
    "Engine.Light",
    "Engine.Keypoint",
    "Engine.ClipMarker",
    "Engine.PolyMarker",
    "Engine.Note",
    "Engine.Camera",
    "Engine.PathNode",
    "Engine.Scout",
    "Engine.InterpolationPoint",
    "Engine.Projectile",
    "Engine.LineOfSightTrigger",
    "Engine.Sound",
    "Engine.AudioSubsystem",
    "Engine.BeamEmitter",
    "Engine.Client",
    "Engine.Viewport",
    "Engine.RenderDevice",
    "Engine.ServerCommandlet",
    "Engine.GlobalTempObjects",
    "Engine.Polys",
    "Engine.Font",
    "Engine.Input",
    "Engine.Console",
    "Engine.LevelBase",
    "Engine.Level",
    "Engine.Primitive",
    "Engine.MeshInstance",
    "Engine.LodMeshInstance",
    "Engine.Mesh",
    "Engine.LodMesh",
    "Engine.ProxyBitmapMaterial",
    "Engine.TexCoordMaterial",
    "Engine.Modifier",
    "Engine.ColorModifier",
    "Engine.Shader",
    "Engine.Combiner",
    "Engine.TexModifier",
    "Engine.TexPanner",
    "Engine.TexScaler",
    "Engine.TexRotator",
    "Engine.TexOscillator",
    "Engine.TexEnvMap",
    "Engine.TexMatrix",
    "Engine.FinalBlend",
    "Engine.MeshEmitter",
    "Engine.Model",
    "Engine.ProjectorPrimitive",
    "Engine.RenderResource",
    "Engine.VertexStreamBase",
    "Engine.VertexStreamVECTOR",
    "Engine.VertexStreamCOLOR",
    "Engine.VertexStreamUV",
    "Engine.VertexStreamPosNormTex",
    "Engine.VertexBuffer",
    "Engine.IndexBuffer",
    "Engine.SkinVertexBuffer",
    "Engine.SceneManager",
    "Engine.ActionMoveCamera",
    "Engine.ActionPause",
    "Engine.SubActionFade",
    "Engine.SubActionTrigger",
    "Engine.SubActionFOV",
    "Engine.SubActionOrientation",
    "Engine.SubActionGameSpeed",
    "Engine.SubActionSceneSpeed",
    "Engine.LookTarget",
    "Engine.MeshEditProps",
    "Engine.AnimEditProps",
    "Engine.SequEditProps",
    "Engine.MeshAnimation",
    "Engine.Animation",
    "Engine.SkeletalMesh",
    "Engine.SkeletalMeshInstance",
    "Engine.SparkEmitter",
    "Engine.SpriteEmitter",
    "Engine.StaticMesh",
    "Engine.StaticMeshInstance",
    "Engine.StaticMeshActor",
    "Engine.TerrainSector",
    "Engine.TerrainPrimitive",
    "Engine.Cubemap",
    "Engine.VolumeTexture",
    "Engine.EchelonEnums",
    "Engine.EAIEvent",
    "Engine.CollisionMeshActor",
    "Engine.EGlow",
    "Engine.ESoftBodyActor",
    "Engine.ERopeActor",
    "Engine.ESoftBody",
    "Engine.ERope",
    "Engine.EOceanPrimitive",
    "Engine.ERainVolume",
    "Engine.ERainPrimitive",
    "Engine.AnimInfo",
    "Engine.ProjectorRenderInfo",
    "Engine.ConvexVolume",
    "Engine.AntiPortalActor",
    "Echelon.EchelonGameInfo",
    "Echelon.PatrolPoint",
    "Echelon.EDoorPoint",
    "Echelon.EDoorMarker",
    "Echelon.EBitTable",
    "Echelon.ESearchManager",
    "Echelon.EGamePlayObjectLight",
    "Echelon.ESoundVolume",
    "Echelon.EGObjectGroup",
    "EchelonIngredient.ESensor",
    "EchelonIngredient.EFlare",
    "EchelonIngredient.EWallMine",
    "EchelonIngredient.ESBPatchActor",
    "EchelonIngredient.ESBRopeActor",
    "EchelonIngredient.ESBChainActor",
    "EchelonIngredient.ESBStripDoorActor",
    "EchelonIngredient.ESBPatch",
    "EchelonIngredient.ESBRope",
    "EchelonIngredient.ESBChain",
    "EchelonIngredient.ESBStripDoor",
    "EchelonHUD.EMenuHUD",
    "EchelonHUD.EMainMenuHUD",
    "ESam.SamAMesh",
];
